### ISSUE TITLE
能否提供下Releases 下载

### ISSUE THREAD

**Issue by yanzhao77** [chinayangxiaowei/marktext-chinese-language-pack#1]
有的地方使用不了百度网盘，能否提供下Releases 下载

**Comment by chinayangxiaowei** [comment]
项目刚建立后上传限制了，现在可以在Releases下载了。

**Comment by chinayangxiaowei** [comment]
> 有的地方使用不了百度网盘，能否提供下Releases 下载

项目刚建立后上传限制了，现在可以在Releases下载了。
