### ISSUE TITLE
能直接给出汉化包吗，修改的不支持M1啊

### ISSUE THREAD

**Issue by cddehsy** [chinayangxiaowei/marktext-chinese-language-pack#2]

**Comment by chinayangxiaowei** [comment]
每个系统编译出来的资源包不一样，所以需要每个系统进行一次替换，比较麻烦。正在实现i18n，已经完成了90%左右了，语言文件从外部读取，完成后将定期与主分支同步。

**Comment by chinayangxiaowei** [comment]
> _No description provided._

每个系统编译出来的资源包不一样，所以需要每个系统进行一次替换，比较麻烦。正在实现i18n，已经完成了90%左右了，翻译字典从外部语言包文件读取，完成后将定期与主分支同步。

**Comment by MUJ1** [comment]
release在哪啊求

**Comment by chinayangxiaowei** [comment]
> release在哪啊求

https://github.com/chinayangxiaowei/marktext-chinese-language-pack/releases

**Comment by chinayangxiaowei** [comment]
> _No description provided._

现在你可以自己编译所需要平台的版本了，安装readme说明编译即可。暂时只支持中文。

**Comment by chinayangxiaowei** [comment]
> _No description provided._

现在你可以自己编译所需要平台的版本了，按照readme说明编译即可。暂时只支持中文。

**Comment by Qicloud-W** [comment]
m1 好像不支持啊大佬

**Comment by chinayangxiaowei** [comment]
已支持M1
