### ISSUE TITLE
where is linux version

### ISSUE THREAD

**Issue by manuel76413** [chinayangxiaowei/marktext-chinese-language-pack#3]
555...

**Comment by chinayangxiaowei** [comment]
> 555...

Now you can compile it yourself, prepare your own language files to "translate-resources" folder and compile it.

**Comment by chinayangxiaowei** [comment]
> 555...

Now you can compile it yourself,  Only Chinese is supported for now.

**Comment by chinayangxiaowei** [comment]
> > 555...
> 
> Now you can compile it yourself, Only Chinese is supported for now.

已上传Linux版本
