### ISSUE TITLE
Need Linux Support!

### ISSUE THREAD

**Issue by MALossov** [chinayangxiaowei/marktext-chinese-language-pack#4]
Can it be supported for UBUNTU?Or other Linux?Or we can build it by its source code?

**Comment by chinayangxiaowei** [comment]
> Can it be supported for UBUNTU?Or other Linux?Or we can build it by its source code?

Now you can compile it yourself, prepare your own language files to "translate-resources" folder and compile it.

**Comment by 89ck** [comment]
能你给编译个， 我直接用不？？ 英文读起来费劲儿， 缺点内味儿

**Comment by chinayangxiaowei** [comment]
> 能你给编译个， 我直接用不？？ 英文读起来费劲儿， 缺点内味儿

已上传Linux版本
