### ISSUE TITLE
一个汉化方面的小问题

### ISSUE THREAD

**Issue by NewbingandBard** [chinayangxiaowei/marktext-chinese-language-pack#6]
<img width="305" alt="汉化问题" src="https://github.com/chinayangxiaowei/marktext-chinese-language-pack/assets/136331279/668a51ce-e806-4fbf-966b-d6e49c87e23a">

首先十分感谢Marktext的原作者以及汉化版作者！经过使用，发现了一些微小的问题。现提出议题。

**平台**：Mac OS Apple Silicon
**版本**：v0.17.1 (Latest)
**问题所在**：汉化部分有错别字，目前发现的是“剧中”（“居中”）

希望 chinayangxiaowei🧑‍🎓 可以进行修复 😊
Thanks!

**Comment by chinayangxiaowei** [comment]
已修复
